#!/bin/bash
# -*- mode: sh -*-

PYENV_ROOT="${PYENV_ROOT:-$HOME/.pyenv}"

python_working=0

if [ -n "$BASHPROF_USE_PYENV" ]; then
    verbose "Configuring Pyenv"
    if [ ! -d "$PYENV_ROOT" ]; then
        important "Couldn't find pyenv at $PYENV_ROOT; performing first-time installation..."
        git clone https://github.com/pyenv/pyenv.git "$PYENV_ROOT" || failure "Failed to clone pyenv"
    fi
    PATH="$PYENV_ROOT/bin:$PATH"
    if command -v pyenv 1>/dev/null 2>&1; then
        eval "$(pyenv init -)"
        export PYENV_ROOT
        export PATH

        if [ "$(pyenv global)" == "system" ]; then
            python_working=1
            warning "Pyenv is installed, but no isolated global version is configured."
            warning "You must use 'pyenv install' to install a Python version before Python operations will function."
            warning "If you encounter a build failure, make sure dependencies are installed."
            warning "You can find these requirements here: https://github.com/pyenv/pyenv/wiki"
        fi
    else
        python_working=1
        warning "Pyenv executable not found; operations requiring Python will not function."
    fi
else
    python_working=1
    verbose "Skipping Pyenv configuration; operations requiring Python will not function."
fi

function bp_python_working() {
    return "$python_working"
}
